baseURL = 'https://wewnumam.github.io/'
languageCode = 'en-us'
title = 'Ahmad Adillaumam'
theme = 'ananke'

[menu]
[[menu.main]]
  identifier = 'articles'
  name = 'ğŸ“„ Articles'
  url = '/articles/'
  weight = -115
[[menu.main]]
  identifier = 'game-design'
  name = 'ğŸ® Game Design'
  url = '/game-design/'
  weight = -110
[[menu.main]]
  identifier = 'programming'
  name = 'ğŸ’» Programming'
  url = '/programming/'
  weight = -105
[[menu.main]]
  identifier = 'about'
  name = 'â“ About Me'
  pre = "<i class='fa fa-circle-question'></i>"
  url = '/about/'
  weight = -100