baseURL = 'https://wewnumam.github.io/'
languageCode = 'en-us'
title = 'Ahmad Adillaumam'
theme = 'ananke'
defaultContentLanguage = 'en'

[languages]
  [languages.en]
    languageName = 'English'
    weight = 1
  [languages.id]
    languageName = 'Indonesia'
    weight = 2

[menu]
[[languages.en.menu.main]]
  identifier = 'articles'
  name = 'ğŸ“„ Articles'
  url = '/articles/'
  weight = -115
[[languages.en.menu.main]]
  identifier = 'game-design'
  name = 'ğŸ® Game Design'
  url = '/game-design/'
  weight = -110
[[languages.en.menu.main]]
  identifier = 'programming'
  name = 'ğŸ’» Programming'
  url = '/programming/'
  weight = -105
[[languages.en.menu.main]]
  identifier = 'about'
  name = 'â“ About Me'
  url = '/about/'
  weight = -100

[[languages.id.menu.main]]
  identifier = 'articles'
  name = 'ğŸ“„ Artikel'
  url = '/id/articles/'
  weight = -115
[[languages.id.menu.main]]
  identifier = 'game-design'
  name = 'ğŸ® Desain Game'
  url = '/id/game-design/'
  weight = -110
[[languages.id.menu.main]]
  identifier = 'programming'
  name = 'ğŸ’» Pemrograman'
  url = '/id/programming/'
  weight = -105
[[languages.id.menu.main]]
  identifier = 'about'
  name = 'â“ Tentang Saya'
  url = '/id/about/'
  weight = -100